### ISSUE TITLE
large number of compiler warnings

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/performance_test#17]
See http://build.ros2.org/view/Fci/job/Fci__nightly-performance_ubuntu_focal_amd64/66/gcc/

**Comment by dirk-thomas** [comment]
@ahcorde Any update on this?

**Comment by ahcorde** [comment]
created a PR upstream https://github.com/eProsima/Fast-DDS/pull/1290

**Comment by ahcorde** [comment]
PR in Fast-DDS is merged 

I launched a build: http://build.ros2.org/view/Fci/job/Fci__nightly-performance_ubuntu_focal_amd64/98/gcc/

**Comment by ahcorde** [comment]
Removed warning. @dirk-thomas can we consider this as done?

 - original http://build.ros2.org/view/Fci/job/Fci__nightly-performance_ubuntu_focal_amd64/66/gcc/

 - Fixed http://build.ros2.org/view/Fci/job/Fci__nightly-performance_ubuntu_focal_amd64/101/gcc/

**Comment by dirk-thomas** [comment]
> can we consider this as done?

Yes, looking much better. Thanks.

**Comment by dirk-thomas** [comment]
The Rolling build has one CMake warning left which would be good to address too: http://build.ros2.org/view/Rci/job/Rci__nightly-performance_ubuntu_focal_amd64/21/cmake/

**Comment by ahcorde** [comment]
@dirk-thomas should I change the type of message to `STATUS` or `DEBUG` ? or do you have any other suggestion ?

**Comment by dirk-thomas** [comment]
@cottsay Any update on this?

**Comment by cottsay** [comment]
I'll try to prioritize this sometime this week.

**Comment by dirk-thomas** [comment]
@cottsay Friendly ping.

**Comment by clalancette** [comment]
I'm going to close this one out, as the original issue with a large number of compiler warnings is solved.  There is still the warning message, but we can handle that separately.
