### ISSUE TITLE
Build failing with Fast-DDS

### ISSUE THREAD

**Issue by ivanpauno** [ros2/performance_test#19]
This line causes an error

https://github.com/ros2/performance_test/blob/df75c932e4c4e7c22cb57b8f120ac04660d9e177/performance_test/src/communication_abstractions/fast_rtps_communicator.hpp#L29

Because that API was deleted in https://github.com/eProsima/Fast-DDS/pull/1227.

---

I only could reproduce locally, I'm not sure why [nightlies](http://build.ros2.org/view/Fci/job/Fci__nightly-performance_ubuntu_focal_amd64) aren't failing.
We're using [2.0.x](https://github.com/ros2/ros2/blob/1a54bc524f00e4ac59de9b665689ea1f7fdfadf5/ros2.repos#L37) Fast-DDS branch in Foxy ...

We're also using `-DPERFORMANCE_TEST_FASTRTPS_ENABLED=1` cmake option there.

**Comment by ivanpauno** [comment]
> I only could reproduce locally, I'm not sure why [nightlies](http://build.ros2.org/view/Fci/job/Fci__nightly-performance_ubuntu_focal_amd64) aren't failing.
> We're using [2.0.x](https://github.com/ros2/ros2/blob/1a54bc524f00e4ac59de9b665689ea1f7fdfadf5/ros2.repos#L37) > Fast-DDS branch in Foxy ...
> 
> We're also using `-DPERFORMANCE_TEST_FASTRTPS_ENABLED=1` cmake option there.

@cottsay @ahcorde any idea why this is not failing on CI and only locally?

**Comment by ivanpauno** [comment]
@richiware FYI

**Comment by richiware** [comment]
Thanks for the ping. I've created a PR #20 fixing this issue.

**Comment by ivanpauno** [comment]
@cottsay friendly ping about this question https://github.com/ros2/performance_test/issues/19#issuecomment-644963348.

Foxy performance tests nightly is supposed to be using FastRTPS 2.0, but it seems not to be using it.

**Comment by cottsay** [comment]
> any idea why this is not failing on CI and only locally?

I'm trying to debug this, but evidently our CI workers took a hike list night. I'll report back if I find anything interesting.
