### ISSUE TITLE
several failing tests

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/performance_test#22]
12 of the 13 test failures are related to linter warnings: http://build.ros2.org/view/Rci/job/Rci__nightly-performance_ubuntu_focal_amd64/lastCompletedBuild/

**Comment by ahcorde** [comment]
PR https://github.com/ros2/performance_test/pull/23

**Comment by ahcorde** [comment]
Contributed upstream too https://gitlab.com/ApexAI/performance_test/-/merge_requests/166

**Comment by dirk-thomas** [comment]
@cottsay Any update on this?

**Comment by dirk-thomas** [comment]
@cottsay Friendly ping.

**Comment by clalancette** [comment]
Given the age of this, I am going to close this out.
