### ISSUE TITLE
👨‍🌾 Gci and Rci report cmake lint errors

### ISSUE THREAD

**Issue by jacobperron** [ros2/performance_test#31]
Both the Galactic and Rolling performance jobs are reporting cmake lint errors for `src/idlgen/opendds/CMakeLists.txt`, which I presume is a third-party package. Probably we should not be running linters on that package.

Example failures:

- https://build.ros2.org/view/Gci/job/Gci__nightly-performance_ubuntu_focal_amd64/24/testReport/junit/(root)/projectroot/lint_cmake/
- https://build.ros2.org/view/Rci/job/Rci__nightly-performance_ubuntu_focal_amd64/351/testReport/

**Comment by clalancette** [comment]
Fixed by #38, so closing.
