### ISSUE TITLE
Building is failing on Rolling/Jammy

### ISSUE THREAD

**Issue by j-rivero** [ros2/performance_test#39]
nightly builds on Rolling are failing  with:
```
09:20:15 --- stderr: performance_test 
09:20:15 CMake Deprecation Warning at /tmp/ws/install_isolated/rosidl_cmake/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
09:20:15   Use rosidl_get_typesupport_target() and target_link_libraries() instead of
09:20:15   rosidl_target_interfaces()
09:20:15 Call Stack (most recent call first):
09:20:15   CMakeLists.txt:280 (rosidl_target_interfaces)
09:20:15 
09:20:15 
09:20:15 CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
09:20:15 Please set them or make sure they are set and tested correctly in the CMake files:
09:20:15 /tmp/ws2/src/performance_test/performance_test/include_directories
09:20:15    used as include directory in directory /tmp/ws2/src/performance_test/performance_test
09:20:15 
09:20:15 CMake Generate step failed.  Build files cannot be regenerated correctly.
09:20:15 ---
```

As the CMake deprecation suggest, the instruction can be changed to use new `rosidl_get_typesupport_target()` but @cottsay mention that we should prefer to fix the underlying problem instead of using new stuff in this fork.

I've been looking into it and found a workaround:
[This line](https://github.com/ros2/performance_test/blob/master/performance_test/CMakeLists.txt#L382) in CMakeLists.txt is calling the `rosidl_target_interfaces` function. This function somehow [assumes](https://github.com/ros2/rosidl/blob/master/rosidl_cmake/cmake/rosidl_target_interfaces.cmake#L54) that the the idl target (`performance_test__rosidl_typesupport_cpp`) has always a valid `INTERFACE_INCLUDE_DIRECTORIES` property. In the case of this package it is returning NOTFOUND and thus failing in a later step. It can be patched easily using:

```diff
diff --git a/rosidl_cmake/cmake/rosidl_target_interfaces.cmake b/rosidl_cmake/cmake/rosidl_target_interfaces.cmake
index 7aca8c6..f3d08eb 100644
--- a/rosidl_cmake/cmake/rosidl_target_interfaces.cmake
+++ b/rosidl_cmake/cmake/rosidl_target_interfaces.cmake
@@ -52,6 +52,8 @@ function(rosidl_target_interfaces target interface_target typesupport_name)
 
   add_dependencies(${target} ${interface_target})
   get_target_property(include_directories ${typesupport_target} INTERFACE_INCLUDE_DIRECTORIES)
-  target_include_directories(${target} PUBLIC ${include_directories})
+  if(${include_directories})
+    target_include_directories(${target} PUBLIC ${include_directories})
+  endif()
   target_link_libraries(${target} ${typesupport_target})
 endfunction()
```

That make this package to compile and my local test also make the whole ros2 stack to build. There is yet an unanswered question for me: why other packages don't need this change and why there is no include_directories in this target.

**Comment by cottsay** [comment]
@sloretz has been making some much needed cleanups to the IDL targets lately, and it's possible that the include directories were dropped from the `_typesupport_cpp` targets for some reason.

I can't see how your proposed change could regress a package that's already building successfully, and it implements a more "defensive" pattern anyway. At worst, it kicks the problem upstream a little further, so it seems like a reasonably safe thing to do. Could you please open a PR into `rosidl_cmake` and we can continue discussion there?

**Comment by sloretz** [comment]
I see nothing wrong with the proposed change either. I think it's a good one for a backport. Now that Humble has branched maybe it's a good time to drop `rosidl_target_interfaces` from Rolling.

>  There is yet an unanswered question for me: why other packages don't need this change and why there is no include_directories in this target.

It looks like target generated by `rosidl_typesupport_cpp` used to populate `INTERFACE_INCLUDE_DIRECTORIES`:

https://github.com/ros2/rosidl_typesupport/blob/97bc0a7716f7346dc0a34eeaba2e9b658f59beb5/rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake#L103-L107

and that got removed in the cleanup. The `$<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/rosidl_generator_cpp>` is now gotten transitively from the target generated by `rosidl_generator_cpp`, and the `$<INSTALL_INTERFACE:include>` was unnecessary.

https://github.com/ros2/rosidl_typesupport/pull/123/files#diff-86d180afe7643ad0258bd4096cbddfa8828154594180b8a384a30f4052e82c1bL103-L107

**Comment by j-rivero** [comment]
> I see nothing wrong with the proposed change either. I think it's a good one for a backport. Now that Humble has branched maybe it's a good time to drop `rosidl_target_interfaces` from Rolling.

I'm going to leave @cottsay to decide on this since he expressed the preference of not touching code in this forked repo.

Thanks guys for feedback.

**Comment by Blast545** [comment]
@j-rivero https://github.com/ros2/rosidl/pull/679 Helped with the first problem on the job, now it's failing with:

https://build.ros2.org/view/Rci/job/Rci__nightly-performance_ubuntu_jammy_amd64/39/
```
gmake[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libtinyxml2.so', needed by 'perf_test'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:632: CMakeFiles/perf_test.dir/all] Error 2
```

I see that in the previous focal jobs [(Example)](https://build.ros2.org/view/Rci/job/Rci__nightly-performance_ubuntu_focal_amd64/501/) `libtinyxml2-dev` is installed as a dependency, and `tinyxml2_vendor` hasn't changed. Do you know what could be wrong there? 

I think this package should include `tinyxml2_vendor` on it's `package.xml`, but that would not explain why the dependency was being read properly before.

**Comment by j-rivero** [comment]
> I see that in the previous focal jobs [(Example)](https://build.ros2.org/view/Rci/job/Rci__nightly-performance_ubuntu_focal_amd64/501/) `libtinyxml2-dev` is installed as a dependency, and `tinyxml2_vendor` hasn't changed. Do you know what could be wrong there?

Previous job seems to be using ROS (1) noetic, there was a line installing some noetic packages:
> Invoking 'apt-get install -q -y -o Debug::pkgProblemResolver=yes build-essential=12.8ubuntu1.1 python3-catkin-pkg-modules=0.4.24-1 python3-colcon-metadata=0.2.5-1 python3-colcon-output=0.2.12-2 python3-colcon-package-selection=0.2.10-2 python3-colcon-parallel-executor=0.2.4-1 python3-colcon-ros=0.3.22-1 python3-colcon-test-result=0.3.8-1 python3-rosdistro-modules=0.8.3-1 ros-noetic-common-msgs=1.13.1-1focal.20220107.010031 ros-noetic-rosbash=1.15.8-1focal.20210726.192129 ros-noetic-roscpp=1.15.14-1focal.20220106.233030 ros-noetic-roscpp-tutorials=0.10.2-1focal.20220106.235817 ros-noetic-roslaunch=1.15.14-1focal.20220106.233833 ros-noetic-rosmsg=1.15.14-1focal.20220106.234759 ros-noetic-rospy-tutorials=0.10.2-1focal.20220107.000622 ros-noetic-tf2-msgs=0.7.5-1focal.20210423.225302'

tinyxml2 was probably installed by the package manager when resolving deps on these packages hence it was hidden the problem on `performance_test` not declaring the dep on tinyxml2_vendor.

New one in the same command does:
> Invoking 'apt-get install -q -y -o Debug::pkgProblemResolver=yes cmake default-jdk google-mock libatomic1 libboost-all-dev libgtest-dev libspdlog-dev libyaml-dev maven python3-argcomplete python3-catkin-pkg-modules python3-dev python3-empy python3-importlib-metadata python3-lark python3-minimal python3-numpy python3-pytest python3-setuptools rti-connext-dds-6.0.1'

Seems like there was a clean up on packages needed inject via apt. I think it should be fine to update performance_test to include the tinyxml2 dependency.

**Comment by clalancette** [comment]
> Seems like there was a clean up on packages needed inject via apt. I think it should be fine to update performance_test to include the tinyxml2 dependency.

That may work, but since `performance_test` doesn't have a direct dependency on `tinyxml2`, it suggests that there is another problem somewhere.  Like a dependency isn't being exported properly.

**Comment by Blast545** [comment]
> Like a dependency isn't being exported properly.

@clalancette Yeah, I think that may be the case. Took some time grepping which of the perf_test package dependencies could rely on `tinyxml2` and I think the problem may be related to `FastRTPS-DDS`. 

I see the package depends on `tinyxml2` here:
https://github.com/eProsima/Fast-DDS/blob/c8a9f196517d463d4cbfe9085247ad2c9aa00b54/package.xml#L22

And it later depends on it as a "third party dependency" here:
https://github.com/eProsima/Fast-DDS/blob/c8a9f196517d463d4cbfe9085247ad2c9aa00b54/CMakeLists.txt#L164
I don't know if it's exported properly at that point.

**Comment by cottsay** [comment]
This should be explicitly added to the package installation list as was done here: https://github.com/ros2/ros_buildfarm_config/pull/227

See that PR for justification.

**Comment by Blast545** [comment]
@j-rivero The rolling performance jobs built successfully: https://build.ros2.org/view/Rci/job/Rci__nightly-performance_ubuntu_jammy_amd64/41/

Thanks for pushing this, I think this issue can be closed.
(How to proceed with 530 failures is a different question)

**Comment by clalancette** [comment]
> (How to proceed with 530 failures is a different question)

This is a tangent, but I think a lot of them are because https://github.com/ros2/buildfarm_perf_test needs to be updated.  In particular, we removed `ready_fn` in Rolling/Humble, so all uses of it in that tree need to be removed.
