### ISSUE TITLE
Nightly performance test jobs fail because of Fast-DDS update

### ISSUE THREAD

**Issue by clalancette** [ros2/performance_test#41]
The https://build.ros2.org/view/Rci/job/Rci__nightly-performance_ubuntu_jammy_amd64/ job has been failing to build since February 1, 2024, which coincides with when we updated Fast-DDS to version 2.13.x (https://github.com/ros2/ros2/pull/1510).

After debugging the failure, I found out the following:

* This repository bundles a version of [fastrtpsgen.jar](https://github.com/ros2/performance_test/blob/7081dd3fae9d1bfe985a94858b6c96650fd1bb4b/performance_test/bin/fastrtpsgen.jar) inside of it.  This is used to generate DDS messages as specified in https://github.com/ros2/performance_test/tree/7081dd3fae9d1bfe985a94858b6c96650fd1bb4b/performance_test/src/msg .
* Because ROS 2 does not have a copy of `fastrtpsgen` inside of it, the bundled fastrtpsgen.jar is always used in these tests.  
* Looking at the history, from what I can tell the last time it was updated was [in 2019](https://github.com/ros2/performance_test/commit/aee932fc6c790cd9c4b8e10b78b8fe16d6cd2a10), to support fastrtps v1.7.1.
* In https://github.com/ros2/performance_test/commit/569ba4f1d29c17fe87b78812fd2b5cb79eb0076c, I updated this to the latest fastrtpsgen.jar from https://github.com/eProsima/Fast-DDS-Gen/tree/07fed5d02c34d3bcb6d91963b4f3ac29234b47ae .  Unfortunately, that fails to build because the header file `fastcdr/cdr/fixed_size_string.hpp` doesn't exist in the version of Fast-CDR ROS 2 currently uses (https://github.com/eProsima/Fast-CDR/tree/1.1.x).
* I also tried updating to Fast-DDS-Gen version 2.5.1, which is right before the change where `fastcdr/cdr/fixed_size_string.hpp` was introduced.  Unfortunately, that doesn't work either because the GEN_API_VER as exported by Fast-DDS is 2, which the GEN_API_VER as expected by Fast-DDS-Gen is 1.

So it seems we are kind of stuck in how to fix this.  @EduPonz @MiguelCompany we could use some advice on how to move forward to fix this.  Thanks.

**Comment by EduPonz** [comment]
Hi @clalancette,

I think you were going in the right direction. Since we released Fast CDR v2.0.0, we made Fast DDS Gen be able to generate code for both v1 and v2 of CDR. By default it generates for v2, but you can control this using the `-cdr` flag (see [here](https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/usage/usage.html#supported-options)).

On a side note, we are preparing PRs to upgrade Fast CDR to v2 in Rolling for the end of the month or so, so it may be a good a idea to already use Fast DDS Gen here with `-cdr both` so that when we make the transition nothing breaks.

**Comment by clalancette** [comment]
> On a side note, we are preparing PRs to upgrade Fast CDR to v2 in Rolling for the end of the month or so, so it may be a good a idea to already use Fast DDS Gen here with `-cdr both` so that when we make the transition nothing breaks.

Ah, thanks.  I'll try to pass `-cdr both` and see what happens.

**Comment by clalancette** [comment]
OK, so building with `-cdr both` didn't work; I got a huge number of link errors.

But building with `-cdr v1` does seem to work, even though it won't be future compatible.  I'm going to open a PR that makes that update for now, and we can revisit `both` when we update to Fast-CDR 2.

**Comment by MiguelCompany** [comment]
@clalancette I'd say #42 has fixed this, so it can be closed

**Comment by clalancette** [comment]
> @clalancette I'd say #42 has fixed this, so it can be closed

Yes and no.  It fixed it for Rolling, but that then broke Humble.  We'll need to follow-up there, probably by creating a new humble-specific branch.

**Comment by wjwwood** [comment]
Waiting on https://github.com/ros2/buildfarm_perf_tests/pull/112 (based on comments in our issue triage meeting)

**Comment by clalancette** [comment]
All merged in, so closing this out now.
