### ISSUE TITLE
:farmer: cpplint include_order test regressions in all ros2 distributions

### ISSUE THREAD

**Issue by Crola1702** [ros2/performance_test#48]
# Description

cppplint shows multiple failures due to include_order in various files from performance_test repo.

Reference builds: 
* [RollingPerformance#57](https://build.ros2.org/job/Rci__nightly-performance_ubuntu_noble_amd64/57/#showFailuresLink)
* [JazzyPerformance#19](https://build.ros2.org/job/Jci__nightly-performance_ubuntu_noble_amd64/19/#showFailuresLink)
* [IronPerformance#109](https://build.ros2.org/job/Ici__nightly-performance_ubuntu_jammy_amd64/109/#showFailuresLink)
* [HumblePerformance#245](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/#showFailuresLink)

Most of the test regressions are related to cpplint include_order

<details>
<summary>
<h4>Test regressions:</h4>
</summary>

* [projectroot.cpplint](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/(root)/projectroot/cpplint/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/communication_abstractions/resource_manager.hpp:48)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_communication_abstractions_resource_manager_hpp_48_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/communication_abstractions/resource_manager.hpp:49)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_communication_abstractions_resource_manager_hpp_49_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/communication_abstractions/resource_manager.hpp:50)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_communication_abstractions_resource_manager_hpp_50_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/communication_abstractions/ros2_callback_communicator.hpp:20)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_communication_abstractions_ros2_callback_communicator_hpp_20_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/communication_abstractions/ros2_callback_communicator.hpp:21)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_communication_abstractions_ros2_callback_communicator_hpp_21_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/communication_abstractions/ros2_communicator.hpp:21)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_communication_abstractions_ros2_communicator_hpp_21_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/communication_abstractions/ros2_communicator.hpp:22)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_communication_abstractions_ros2_communicator_hpp_22_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/communication_abstractions/ros2_waitset_communicator.hpp:20)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_communication_abstractions_ros2_waitset_communicator_hpp_20_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/communication_abstractions/ros2_waitset_communicator.hpp:21)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_communication_abstractions_ros2_waitset_communicator_hpp_21_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/communication_abstractions/ros2_waitset_communicator.hpp:22)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_communication_abstractions_ros2_waitset_communicator_hpp_22_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/communication_abstractions/ros2_waitset_communicator.hpp:23)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_communication_abstractions_ros2_waitset_communicator_hpp_23_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/data_running/data_runner_base.hpp:19)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_data_running_data_runner_base_hpp_19_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/data_running/data_runner_factory.cpp:19)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_data_running_data_runner_factory_cpp_19_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/data_running/data_runner_factory.cpp:20)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_data_running_data_runner_factory_cpp_20_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_configuration/experiment_configuration.cpp:18)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_configuration_experiment_configuration_cpp_18_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_configuration/experiment_configuration.cpp:20)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_configuration_experiment_configuration_cpp_20_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_configuration/experiment_configuration.cpp:21)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_configuration_experiment_configuration_cpp_21_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_configuration/experiment_configuration.cpp:22)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_configuration_experiment_configuration_cpp_22_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_configuration/experiment_configuration.cpp:23)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_configuration_experiment_configuration_cpp_23_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_configuration/experiment_configuration.hpp:21)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_configuration_experiment_configuration_hpp_21_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_configuration/experiment_configuration.hpp:22)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_configuration_experiment_configuration_hpp_22_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_configuration/experiment_configuration.hpp:23)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_configuration_experiment_configuration_hpp_23_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_configuration/experiment_configuration.hpp:24)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_configuration_experiment_configuration_hpp_24_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_configuration/external_info_storage.hpp:21)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_configuration_external_info_storage_hpp_21_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_configuration/external_info_storage.hpp:22)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_configuration_external_info_storage_hpp_22_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_execution/analyze_runner.cpp:15)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_execution_analyze_runner_cpp_15_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_execution/analyze_runner.cpp:16)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_execution_analyze_runner_cpp_16_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_execution/analyze_runner.cpp:17)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_execution_analyze_runner_cpp_17_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_execution/analyze_runner.cpp:18)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_execution_analyze_runner_cpp_18_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_execution/analyze_runner.cpp:19)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_execution_analyze_runner_cpp_19_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_execution/analyze_runner.cpp:20)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_execution_analyze_runner_cpp_20_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_execution/analyze_runner.cpp:21)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_execution_analyze_runner_cpp_21_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_execution/analyze_runner.cpp:29)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_execution_analyze_runner_cpp_29_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/experiment_execution/analyze_runner.cpp:30)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_experiment_execution_analyze_runner_cpp_30_/)
* [performance_test.cpplint.build/include_order [4] (/tmp/ws2/src/performance_test/performance_test/src/utilities/cpu_usage_tracker.hpp:19)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/245/testReport/junit/performance_test/cpplint/build_include_order__4____tmp_ws2_src_performance_test_performance_test_src_utilities_cpu_usage_tracker_hpp_19_/)

</details>

<details>
<summary>
<h4>Affected files:</h4>
</summary>

* resource_manager.hpp:48
* resource_manager.hpp:49
* resource_manager.hpp:50
* ros2_callback_communicator.hpp:20
* ros2_callback_communicator.hpp:21
* ros2_communicator.hpp:21
* ros2_communicator.hpp:22
* ros2_waitset_communicator.hpp:20
* ros2_waitset_communicator.hpp:21
* ros2_waitset_communicator.hpp:22
* ros2_waitset_communicator.hpp:23
* data_runner_base.hpp:19
* data_runner_factory.cpp:19
* data_runner_factory.cpp:20
* experiment_configuration.cpp:18
* experiment_configuration.cpp:20
* experiment_configuration.cpp:21
* experiment_configuration.cpp:22
* experiment_configuration.cpp:23
* experiment_configuration.hpp:21
* experiment_configuration.hpp:22
* experiment_configuration.hpp:23
* experiment_configuration.hpp:24
* external_info_storage.hpp:21
* external_info_storage.hpp:22
* analyze_runner.cpp:15
* analyze_runner.cpp:16
* analyze_runner.cpp:17
* analyze_runner.cpp:18
* analyze_runner.cpp:19
* analyze_runner.cpp:20
* analyze_runner.cpp:21
* analyze_runner.cpp:29
* analyze_runner.cpp:30
* cpu_usage_tracker.hpp:19

</details>

**Comment by Blast545** [comment]
I fixed this on main with: https://github.com/ros2/performance_test/pull/53

Please do not close the issue until this is backported to the other distros.

**Comment by Blast545** [comment]
This was fixed after #55 and #56, @Crola1702 I don't have admin powers here, feel free to close this one.
