### ISSUE TITLE
:woman_farmer: uncrustify   regression on `connext_dds_micro_communicator` test for all distros 

### ISSUE THREAD

**Issue by claraberendsen** [ros2/performance_test#49]
#### Description 
There seems to be a test regression on all distros for the test `connext_dds_micro_communicator`

The error is 
```
--- src/communication_abstractions/connext_dds_micro_communicator.hpp
+++ src/communication_abstractions/connext_dds_micro_communicator.hpp.uncrustify
@@ -295 +295,2 @@
-  static auto init_data(T & data)->decltype (data.header_.frame_id_, void ()) {
+  static auto init_data(T & data)->decltype (data.header_.frame_id_, void ())
+  {
@@ -317 +318,2 @@
-  static auto init_fields(T & data)->decltype (data.fields_, void ()) {
+  static auto init_fields(T & data)->decltype (data.fields_, void ())
+  {
```
#### Affected builds
- Humble:  [Hci__nightly-performance_ubuntu_jammy_amd64#247](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/247)
- Rolling: [Rci__nightly-performance_ubuntu_noble_amd64#60](https://build.ros2.org/job/Rci__nightly-performance_ubuntu_noble_amd64/60)
- Jazzy: [Jci__nightly-performance_ubuntu_noble_amd64#20](https://build.ros2.org/job/Jci__nightly-performance_ubuntu_noble_amd64/20)
- Iron: [Ici__nightly-performance_ubuntu_noble_amd64#109](https://build.ros2.org/view/Ici/job/Ici__nightly-performance_ubuntu_jammy_amd64/109)
#### Additional information
File 
https://github.com/ros2/performance_test/blob/7081dd3fae9d1bfe985a94858b6c96650fd1bb4b/performance_test/src/communication_abstractions/connext_dds_micro_communicator.hpp

**Comment by Blast545** [comment]
I fixed this on main with: https://github.com/ros2/performance_test/pull/53, feel free to close it whenever you want, as I will be tracking the backports with https://github.com/ros2/performance_test/issues/48, which is technically the same issue.

**Comment by clalancette** [comment]
Thanks!
