### ISSUE TITLE
:woman_farmer: lint_cmake regression on `src/idlgen/opendds/CMakeLists` for all distros

### ISSUE THREAD

**Issue by claraberendsen** [ros2/performance_test#50]
#### Description 
There are `lint_cmake` warnings on the file `src/idlgen/opendds/CMakeLists`. 
The error message shows

```
Lines should be <= 140 characters long
```
#### Regressions
[performance_test.lint_cmake.linelength (src/idlgen/opendds/CMakeLists.txt:22)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/247/testReport/junit/performance_test/lint_cmake/linelength__src_idlgen_opendds_CMakeLists_txt_22_/)
[performance_test.lint_cmake.linelength (src/idlgen/opendds/CMakeLists.txt:23)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/247/testReport/junit/performance_test/lint_cmake/linelength__src_idlgen_opendds_CMakeLists_txt_23_/)
[performance_test.lint_cmake.linelength (src/idlgen/opendds/CMakeLists.txt:102)](https://build.ros2.org/job/Hci__nightly-performance_ubuntu_jammy_amd64/247/testReport/junit/performance_test/lint_cmake/linelength__src_idlgen_opendds_CMakeLists_txt_102_/)

**Comment by Crola1702** [comment]
I think this was fixed by: https://github.com/ros2/performance_test/pull/38
